FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++ git

RUN npm install -g nodemon

COPY package*.json ./
COPY next.config.mjs ./
COPY postcss.config.mjs ./
COPY tailwind.config.js ./

RUN npm ci

COPY . .

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_SHARP_PATH=/tmp/node_modules/sharp
ENV NEXT_RUNTIME="nodejs"

ARG AIRTABLE_API_KEY
ARG AIRTABLE_BASE_ID
ARG NEXT_PUBLIC_AIRTABLE_API_KEY
ARG NEXT_PUBLIC_AIRTABLE_BASE_ID
ARG BOOQABLE_API_KEY
ARG BOOQABLE_BASE_URL
ARG NEXT_PUBLIC_BOOQABLE_API_KEY
ARG NEXT_PUBLIC_BOOQABLE_BASE_URL
ARG AIRTABLE_TAMPLATE_API_KEY
ARG AIRTABLE_TAMPLATE_BASE_ID
ARG NEXT_PUBLIC_AIRTABLE_TAMPLATE_API_KEY
ARG NEXT_PUBLIC_AIRTABLE_TAMPLATE_BASE_ID
ARG AIRTABLE_ACTIVITY_LOG_API_KEY
ARG AIRTABLE_ACTIVITY_LOG_BASE_ID
ARG NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_API_KEY
ARG NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_BASE_ID

ENV AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
ENV AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
ENV NEXT_PUBLIC_AIRTABLE_API_KEY=${NEXT_PUBLIC_AIRTABLE_API_KEY}
ENV NEXT_PUBLIC_AIRTABLE_BASE_ID=${NEXT_PUBLIC_AIRTABLE_BASE_ID}
ENV BOOQABLE_API_KEY=${BOOQABLE_API_KEY}
ENV BOOQABLE_BASE_URL=${BOOQABLE_BASE_URL}
ENV NEXT_PUBLIC_BOOQABLE_API_KEY=${NEXT_PUBLIC_BOOQABLE_API_KEY}
ENV NEXT_PUBLIC_BOOQABLE_BASE_URL=${NEXT_PUBLIC_BOOQABLE_BASE_URL}
ENV AIRTABLE_TAMPLATE_API_KEY=${AIRTABLE_TAMPLATE_API_KEY}
ENV AIRTABLE_TAMPLATE_BASE_ID=${AIRTABLE_TAMPLATE_BASE_ID}
ENV NEXT_PUBLIC_AIRTABLE_TAMPLATE_API_KEY=${NEXT_PUBLIC_AIRTABLE_TAMPLATE_API_KEY}
ENV NEXT_PUBLIC_AIRTABLE_TAMPLATE_BASE_ID=${NEXT_PUBLIC_AIRTABLE_TAMPLATE_BASE_ID}
ENV AIRTABLE_ACTIVITY_LOG_API_KEY=${AIRTABLE_ACTIVITY_LOG_API_KEY}
ENV AIRTABLE_ACTIVITY_LOG_BASE_ID=${AIRTABLE_ACTIVITY_LOG_BASE_ID}
ENV NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_API_KEY=${NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_API_KEY}
ENV NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_BASE_ID=${NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_BASE_ID}
RUN echo "# Airtable Configuration" > .env && \
    echo "AIRTABLE_API_KEY=${AIRTABLE_API_KEY}" >> .env && \
    echo "AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_API_KEY=${NEXT_PUBLIC_AIRTABLE_API_KEY}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_BASE_ID=${NEXT_PUBLIC_AIRTABLE_BASE_ID}" >> .env && \
    echo "" >> .env && \
    echo "# Booqable Configuration" >> .env && \
    echo "BOOQABLE_API_KEY=${BOOQABLE_API_KEY}" >> .env && \
    echo "BOOQABLE_BASE_URL=${BOOQABLE_BASE_URL}" >> .env && \
    echo "NEXT_PUBLIC_BOOQABLE_API_KEY=${NEXT_PUBLIC_BOOQABLE_API_KEY}" >> .env && \
    echo "NEXT_PUBLIC_BOOQABLE_BASE_URL=${NEXT_PUBLIC_BOOQABLE_BASE_URL}" >> .env && \
    echo "" >> .env && \
    echo "# Airtable Template Configuration" >> .env && \
    echo "AIRTABLE_TAMPLATE_API_KEY=${AIRTABLE_TAMPLATE_API_KEY}" >> .env && \
    echo "AIRTABLE_TAMPLATE_BASE_ID=${AIRTABLE_TAMPLATE_BASE_ID}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_TAMPLATE_API_KEY=${NEXT_PUBLIC_AIRTABLE_TAMPLATE_API_KEY}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_TAMPLATE_BASE_ID=${NEXT_PUBLIC_AIRTABLE_TAMPLATE_BASE_ID}" >> .env && \
    echo "" >> .env && \
    echo "# Airtable Activity Log Configuration" >> .env && \
    echo "AIRTABLE_ACTIVITY_LOG_API_KEY=${AIRTABLE_ACTIVITY_LOG_API_KEY}" >> .env && \
    echo "AIRTABLE_ACTIVITY_LOG_BASE_ID=${AIRTABLE_ACTIVITY_LOG_BASE_ID}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_API_KEY=${NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_API_KEY}" >> .env && \
    echo "NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_BASE_ID=${NEXT_PUBLIC_AIRTABLE_ACTIVITY_LOG_BASE_ID}" >> .env 

EXPOSE 3001

CMD ["npm", "run", "dev"]