services:
  web:
    build:
      context: .
      args:
        BOOQABLE_COMPANY_SLUG: ${BOOQABLE_COMPANY_SLUG}
        BOOQABLE_API_KEY: ${BOOQABLE_API_KEY}
        GMAIL_EMAIL: ${GMAIL_EMAIL}
        GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}
        AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
        AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
        NEXT_PUBLIC_AIRTABLE_API_KEY: ${AIRTABLE_API_KEY}
        NEXT_PUBLIC_AIRTABLE_BASE_ID: ${AIRTABLE_BASE_ID}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
      - NEXT_PUBLIC_AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - NEXT_PUBLIC_AIRTABLE_BASE_ID=${AIRTABLE_BASE_ID}
    volumes:
      - F:/Downloads/Archive:/app     
      - /app/node_modules               
    command: npm run dev                
